Calculator: MathLib.Operations Class Reference
MathLib.Operations Class Reference
Poskytuje metódy pre základné a pokročilé matematické operácie.
Static Public Member Functions
static double StandardDeviation (List< double > values)
Vypočíta smerodajnú odchýlku zoznamu hodnôt.
static double Factorial (int number)
Vypočíta faktoriál čísla.
static double Log (double a, double @base)
Vypočíta logaritmus čísla pri zadanom základe.
static double Root (double a, double exponent)
Vypočíta n-tú odmocninu z čísla.
static double Power (double num, double exp)
Vypočíta umocnenie čísla na daný exponent.
static double Add (double a, double b)
Sčíta dve čísla.
static double Subtract (double a, double b)
Odčíta druhé číslo od prvého.
static double Multiply (double a, double b)
Vynásobí dve čísla.
static double Divide (double a, double b)
Vykoná delenie dvoch čísel.
Detailed Description
Poskytuje metódy pre základné a pokročilé matematické operácie.
Definition at line 28 of file Operations.cs.
Member Function Documentation
Add()
static double MathLib.Operations.Add (double a, double b) inline static
Sčíta dve čísla.
Sčíta dve čísla.
Parameters
a Prvé číslo.
b Druhé číslo.
Returns
Súčet čísiel a a b.
Exceptions
OverflowException Vyvolaná, ak pretečie rozsah pre kladné čísla.
Definition at line 180 of file Operations.cs.
Referenced by MathLib.Operations.StandardDeviation().
Divide()
static double MathLib.Operations.Divide (double a, double b) inline static
Vykoná delenie dvoch čísel.
Vykoná delenie dvoch čísel.
Parameters
a Čitateľ.
b Menovateľ.
Returns
Výsledok delenia a / b.
Exceptions
DivideByZeroException Vyvolaná, ak je menovateľ nulový.
Definition at line 237 of file Operations.cs.
Referenced by MathLib.Operations.StandardDeviation().
Factorial()
static double MathLib.Operations.Factorial (int number) inline static
Vypočíta faktoriál čísla.
Vypočíta faktoriál čísla.
Parameters
number Číslo, ktorého faktoriál sa má vypočítať.
Returns
Faktoriál čísla.
Exceptions
ArgumentException Vyvolaná, ak je číslo záporné.
Definition at line 72 of file Operations.cs.
References MathLib.Operations.Factorial().
Referenced by MathLib.Operations.Factorial().
Log()
static double MathLib.Operations.Log (double a, double @ base) inline static
Vypočíta logaritmus čísla pri zadanom základe.
Vypočíta logaritmus čísla pri zadanom základe.
Parameters
a Číslo, z ktorého sa počíta logaritmus (musí byť kladné).
base Základ logaritmu (musí byť kladný a rôzny od 1).
Returns
Výsledok logaritmu čísla a pri základe base.
Exceptions
IndexOutOfRangeException Vyvolaná, ak a alebo base nie sú platné hodnoty.
Definition at line 109 of file Operations.cs.
Multiply()
static double MathLib.Operations.Multiply (double a, double b) inline static
Vynásobí dve čísla.
Vynásobí dve čísla.
Parameters
a Prvé číslo.
b Druhé číslo.
Returns
Súčin čísiel a a b.
Exceptions
OverflowException Vyvolaná, ak pretečie rozsah pre výsledok násobenia.
Definition at line 216 of file Operations.cs.
Power()
static double MathLib.Operations.Power (double num, double exp) inline static
Vypočíta umocnenie čísla na daný exponent.
Vypočíta umocnenie čísla na daný exponent.
Parameters
num Základ mocniny.
exp Exponent.
Returns
Výsledok umocnenia num na exp.
Exceptions
ArgumentException Vyvolaná, ak je základ aj exponent nula alebo ak je základ záporný a exponent nie je celé číslo.
Definition at line 158 of file Operations.cs.
Referenced by MathLib.Operations.StandardDeviation().
Root()
static double MathLib.Operations.Root (double a, double exponent) inline static
Vypočíta n-tú odmocninu z čísla.
Vypočíta n-tú odmocninu z čísla.
Parameters
a Číslo, z ktorého sa počíta odmocnina.
exponent Exponent (stupeň odmocniny, musí byť nenulový).
Returns
Výsledok n-tej odmocniny čísla a.
Exceptions
IndexOutOfRangeException Vyvolaná, ak exponent je nulový alebo je odmocňované číslo záporné a exponent párny.
Definition at line 129 of file Operations.cs.
Referenced by MathLib.Operations.StandardDeviation().
StandardDeviation()
static double MathLib.Operations.StandardDeviation (List< double > values) inline static
Vypočíta smerodajnú odchýlku zoznamu hodnôt.
Vypočíta smerodajnú odchýlku zoznamu hodnôt.
Parameters
values Zoznam čísel, pre ktoré sa vypočíta smerodajná odchýlka.
Returns
Smerodajná odchýlka vstupného zoznamu.
Exceptions
ArgumentException Vyvolaná, ak je vstupný zoznam prázdny.
Definition at line 39 of file Operations.cs.
References MathLib.Operations.Add(), MathLib.Operations.Divide(), MathLib.Operations.Power(), MathLib.Operations.Root(), and MathLib.Operations.Subtract().
Referenced by StdDevBenchmark.CalculateStdDev(), and StdDevCalculator.Run().
Subtract()
static double MathLib.Operations.Subtract (double a, double b) inline static
Odčíta druhé číslo od prvého.
Odčíta druhé číslo od prvého.
Parameters
a Prvé číslo.
b Druhé číslo.
Returns
Rozdiel čísiel a a b.
Exceptions
OverflowException Vyvolaná, ak pretečie rozsah pre záporné čísla.
Definition at line 198 of file Operations.cs.
Referenced by MathLib.Operations.StandardDeviation().
The documentation for this class was generated from the following file:
src/MathLib/Operations.cs